version: "3.8"

services:
  sftpgo:
    image: drakkan/sftpgo:latest
    container_name: sftpgo
    restart: unless-stopped
    ports:
      - "2022:2022" # SFTP port
      - "8022:8022" # SSH port for admin
      - "2121:2121" # FTP port (if enabled)
      - "50000-50100:50000-50100" # Passive FTP Ports
    environment:
      - SFTPGO_FTPD__BINDINGS__0__PORT=2121
      - SFTPGO_FTPD__BINDINGS__0__FORCE_PASSIVE_IP= # add your IP here
    networks:
      - dokploy-network
    volumes:
      - ftpgo-data:/srv/sftpgo

networks:
  dokploy-network:
    external: true

volumes:
  ftpgo-data: